In [1]:
from keras.models import load_model
model = load_model('model.h5')
#model.summary()

Using TensorFlow backend.


In [13]:
import tkinter as tk
import os
import cv2
import sys
from PIL import Image, ImageTk
import numpy

cancel1 = False
cancel2 = True

root = tk.Tk()
root.title('NTU-EEE-DIP AI CAR by Yeqi, Yuan, Chang')
root.geometry('1300x600')

canvas = tk.Canvas(root,bg='pink',height=180,width=500)
image_path1 = tk.PhotoImage(file='1.png')
image_path2 = tk.PhotoImage(file='tenor.gif')
image1 = canvas.create_image(0,0,anchor='nw',image=image_path1)
image2 = canvas.create_image(230,-20,anchor='nw',image=image_path2)
canvas.place(x=5,y=5)

frm_l =tk.Frame(root)
frm_r =tk.Frame(root)

frm_l.pack(side='left')
frm_r.pack(side='right')
#===================================================================
def hit_me5():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('run forward a bit')

def hit_me6():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn left a bit')

def hit_me7():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn right a bit')

def hit_me8():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('stop car')

def change_cancel2():
    global cancel1,cancel2
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('start')
        cancel2 = False
        cancel1 = True
        
#===================================================================
ll = tk.Label(frm_l,text='discrete control',bg='yellow',font=('Arial',12),width=15,height=3)
ll.pack()

bl1 = tk.Button(frm_l,text='run forward',width=15,height=3,command=hit_me5)
bl1.pack(side='top')

bl2 = tk.Button(frm_l,text='turn left',width=15,height=3,command=hit_me6)
bl2.pack(side='left')

bl3 = tk.Button(frm_l,text='turn right',width=15,height=3,command=hit_me7)
bl3.pack(side='right')

bl4 = tk.Button(frm_l,text='stop',width=15,height=3,command=hit_me8)
bl4.pack(side='bottom')
#===================================================================
lmain = tk.Label(root, compound=tk.CENTER, anchor=tk.CENTER, relief=tk.RAISED)

lmain.pack()

#===================================================================
cap = cv2.VideoCapture(0)
var = tk.StringVar()  
def show_frame():
    global var,cancel2
    if cancel2 == False:
        _, frame = cap.read()
        cv2image1 = cv2.flip(frame,1)
        cv2image2 = cv2.cvtColor(cv2image1, cv2.COLOR_BGR2RGBA)
    
    
        cv2.rectangle(cv2image2,(360,60),(590,290),(0,255,0),5)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(cv2image2,'Put your RIGHT hand in this square!',(300,40),font,0.6,(0,255,0),2,cv2.LINE_AA)
    
        crop_cv2image = cv2image1[63:287,363:587]

        img = crop_cv2image.reshape((1,)+ crop_cv2image.shape )
    
        prediction = model.predict(img)[0]
        print(prediction)
                                                             
        pred_class = list(prediction).index(max(prediction))
    
        print(pred_class)
        if pred_class==1:
            var.set('run forward')
        if pred_class==2:
            var.set('turn left a bit')
        if pred_class==3:
            var.set('turn right')
        if pred_class==0:
            var.set('no instruction')  
    
        l = tk.Label(root,textvariable=var,bg='blue',font=('Arial',22),width=25,height=5)
        l.pack(side='bottom')
    
        prevImg = Image.fromarray(cv2image2)
        imgtk = ImageTk.PhotoImage(image=prevImg)
        lmain.imgtk = imgtk
        lmain.configure(image=imgtk)
        if not cancel2:
            lmain.after(10, show_frame)
#============

def ini_show_frame():
    global var,cancel1 

    _, frame = cap.read()
    cv2image1 = cv2.flip(frame,1)
    cv2image2 = cv2.cvtColor(cv2image1, cv2.COLOR_BGR2RGBA)
    
    
    cv2.rectangle(cv2image2,(360,60),(590,290),(0,255,0),5)
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(cv2image2,'Put your RIGHT then click START!',(320,40),font,0.6,(0,255,0),2,cv2.LINE_AA)
    
    crop_cv2image = cv2image1[63:287,363:587]

    img = crop_cv2image.reshape((1,)+ crop_cv2image.shape ) 
    
    l = tk.Label(root,textvariable=var,bg='blue',font=('Arial',22),width=25,height=5)
    l.pack(side='bottom')
    
    prevImg = Image.fromarray(cv2image2)
    imgtk = ImageTk.PhotoImage(image=prevImg)
    lmain.imgtk = imgtk
    lmain.configure(image=imgtk)
    if cancel1 == False:
        lmain.after(10, ini_show_frame)
    else:
        show_frame()
        
ini_show_frame()
#================
button = tk.Button(frm_l, text="START!", width=15, height=3,command=change_cancel2)
button.pack(side='bottom')        

root.mainloop()

[0.08967485 0.2670485  0.5178578  0.12541896]
2
[0.02483328 0.10639534 0.67295104 0.19582032]
2
[0.42451382 0.23554248 0.30969185 0.03025186]
0
[0.32114753 0.3014098  0.35292488 0.02451774]
2
[0.01690875 0.10201544 0.8729514  0.00812437]
2
[0.0379263  0.16039655 0.7624945  0.03918267]
2
[0.4148675  0.34238812 0.20592813 0.03681628]
0
[0.5852719  0.34308943 0.06276632 0.00887235]
0
[5.6119775e-03 9.7601616e-01 9.3074568e-04 1.7441066e-02]
1
[9.9736857e-01 1.2476353e-03 1.1180255e-03 2.6573928e-04]
0
[9.9890018e-01 6.3893029e-05 9.1818604e-04 1.1762109e-04]
0
[9.9842286e-01 1.0810411e-03 4.0321908e-04 9.2847898e-05]
0
[9.9947482e-01 4.0875262e-04 7.1578579e-05 4.4819986e-05]
0
[9.9841166e-01 1.3649669e-03 1.4730637e-04 7.6028919e-05]
0
[9.9933100e-01 6.1114237e-04 4.6176101e-05 1.1643602e-05]
0
[9.9952126e-01 4.0880864e-04 4.4147040e-05 2.5687899e-05]
0
[9.9890804e-01 9.8261272e-04 4.2623116e-05 6.6674882e-05]
0
[0.3083225  0.6692097  0.00388179 0.01858601]
1
[0.0058139  0.9252041  0.003