In [3]:
from keras import layers
from keras.models import Model, load_model
import keras
from keras.layers import Lambda
model = load_model('model.h5')
#model.summary()

def soft_max(x):
    import tensorflow as tf
    return tf.nn.softmax(x)

from keras import optimizers
rms = optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0)
x = model.output
predictions = Lambda(lambda x: soft_max(x))(x)
model = Model(inputs=model.input, outputs=predictions)
model.compile(optimizer=rms, loss='categorical_crossentropy')

C:\Anaconda3\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [4]:
import tkinter as tk
import os
import cv2
import sys
from PIL import Image, ImageTk
import numpy

cancel = False

root = tk.Tk()
root.title('NTU-EEE-DIP AI CAR by Yeqi, Yuan, Chang')
root.geometry('1300x600')

canvas = tk.Canvas(root,bg='pink',height=180,width=500)
image_path1 = tk.PhotoImage(file='1.png')
image_path2 = tk.PhotoImage(file='tenor.gif')
image1 = canvas.create_image(0,0,anchor='nw',image=image_path1)
image2 = canvas.create_image(230,-20,anchor='nw',image=image_path2)
canvas.place(x=5,y=5)

frm_l =tk.Frame(root)
frm_r =tk.Frame(root)

frm_l.pack(side='left')
frm_r.pack(side='right')
#===================================================================
def hit_me1():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('run forward 1s')

def hit_me2():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn left 1s')

def hit_me3():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn right 1s')

def hit_me4():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('make a turn 180 degree')

def hit_me5():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('run forward a bit')

def hit_me6():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn left a bit')

def hit_me7():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn right a bit')

def hit_me8():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('rotate a bit')
    
        
#===================================================================
ll = tk.Label(frm_l,text='discrete control',bg='yellow',font=('Arial',12),width=15,height=3)
ll.pack()

bl1 = tk.Button(frm_l,text='run forward',width=15,height=3,command=hit_me1)
bl1.pack(side='top')

bl2 = tk.Button(frm_l,text='turn left',width=15,height=3,command=hit_me2)
bl2.pack(side='left')

bl3 = tk.Button(frm_l,text='turn right',width=15,height=3,command=hit_me3)
bl3.pack(side='right')

bl4 = tk.Button(frm_l,text='make a turn',width=15,height=3,command=hit_me4)
bl4.pack(side='bottom')
#===================================================================
# lr = tk.Label(frm_r,text='continous control',bg='yellow',font=('Arial',12),width=15,height=3)
# lr.pack()

# br1 = tk.Button(frm_r,text='run forward',width=15,height=3,command=hit_me5)
# br1.pack(side='top')

# br2 = tk.Button(frm_r,text='turn left',width=15,height=3,command=hit_me6)
# br2.pack(side='left')

# br3 = tk.Button(frm_r,text='turn right',width=15,height=3,command=hit_me7)
# br3.pack(side='right')

# br4 = tk.Button(frm_r,text='make a turn',width=15,height=3,command=hit_me8)
# br4.pack(side='bottom')
#===================================================================
lmain = tk.Label(root, compound=tk.CENTER, anchor=tk.CENTER, relief=tk.RAISED)
#button = tk.Button(root, text="Capture")
lmain.pack()
#button.place(bordermode=tk.INSIDE, relx=0.5, rely=0.9, anchor=tk.CENTER, width=300, height=50)
#button.focus()
#===================================================================
cap = cv2.VideoCapture(0)
var = tk.StringVar()            
def show_frame():
    global var,cancel, prevImg, button

    _, frame = cap.read()
    cv2image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGBA)
    cv2image = cv2.flip(cv2image,1)
    
    cv2.rectangle(cv2image,(30,80),(280,420),(255,0,0),5)
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(cv2image,'Put your LEFT hand in this rectangle!',(20,60),font,0.6,(0,255,0),2,cv2.LINE_AA)
    
    crop_cv2image = cv2image[80:420, 30:280]
    cv2image_gray = cv2.cvtColor(crop_cv2image, cv2.COLOR_RGB2GRAY)
    img = cv2.resize(cv2image_gray,dsize=(28,28),interpolation=cv2.INTER_LINEAR)
    img = img.astype('float32')
    img *= (1/255)
    img = img.reshape((1,)+img.shape + (1,))
    prediction = model.predict(img)
    print(prediction)
    if prediction[0][1]>=0.4:
        var.set('run forward')
    if prediction[0][2]>=0.4:
        var.set('turn left a bit')
    if prediction[0][3]>=0.4:
        var.set('turn right')
    if prediction[0][0]>=0.4:
        var.set('no instruction')  
    
    l = tk.Label(root,textvariable=var,bg='blue',font=('Arial',22),width=25,height=3)
    l.pack(side='bottom')


    prevImg = Image.fromarray(cv2image)
    imgtk = ImageTk.PhotoImage(image=prevImg)
    lmain.imgtk = imgtk
    lmain.configure(image=imgtk)
    if not cancel:
        lmain.after(50, show_frame)
        
show_frame()


root.mainloop()

[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.143

[[0.0000000e+00 3.3354928e-04 0.0000000e+00 9.9966645e-01]]
[[0.0000000e+00 9.9999607e-01 0.0000000e+00 3.9731044e-06]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 7.6489355e-27]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.7057154e-31]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1716058e-29]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 5.9821585e-35]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.2968168e-26]]
[[0.00000e+00 1.00000e+00 0.00000e+00 4.54362e-25]]
[[0.000000e+00 1.000000e+00 0.000000e+00 6.624147e-20]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1391132e-28]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.7918464e-37]]
[[0. 1. 0. 0.]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.8535256e-20]]
[[0.0000000e+00 1.8974350e-07 0.0000000e+00 9.9999976e-01]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.2175872e-10]]
[[0.00000e+00 1.00000e+00 0.00000e+00 5.24101e-13]]
[[0.000000e+00 1.000000e+00 0.000000e+00 9.154922e-13]]
[[0.000000e+00 1.000000e+00 0.000000e+00 5.88132

[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.26494372 0.37224123 0.21913794 0.14367706]]
[[0.01646621 0.10824095 0.6482045  0.22708826]]
[[0.01293852 0.09630791 0.73562986 0.15512374]]
[[0.10956767 0.2889976  0.47008428 0.13135043]]
[[0.24161431 0.38059604 0.25091624 0.12687342]]
[[0.265407   0.3717453  0.2253363  0.13751145]]
[[0.30039638 0.36100397 0.24107483 0.09752482]]
[[0.28904328 0.36368996 0.24405877 0.10320793]]
[[0.26447165 0.37220767 0.21984595 0.14347467]]
[[2.7090699e-09 3.1347190e-05 9.6644269e-04 9.9900228e-01]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0.0000000e+00 1.9303765e-37 0.0000000e+00 1.0000000e+00]]
[[0. 0. 0. 1.]]
[[0. 0. 0. 1.]]
[[0.0000000e+00 2.2491308e-36 0.0000000e+00 1.0000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[0.0000000e+00 2.24