In [1]:
from keras import layers
from keras.models import Model, load_model
import keras
from keras.layers import Lambda
model = load_model('model.h5')
#model.summary()

def soft_max(x):
    import tensorflow as tf
    return tf.nn.softmax(x)

from keras import optimizers
rms = optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0)
x = model.output
predictions = Lambda(lambda x: soft_max(x))(x)
model = Model(inputs=model.input, outputs=predictions)
model.compile(optimizer=rms, loss='categorical_crossentropy')

Using TensorFlow backend.
C:\Anaconda3\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [ ]:
import tkinter as tk
import os
import cv2
import sys
from PIL import Image, ImageTk
import numpy

cancel = False

root = tk.Tk()
root.title('NTU-EEE-DIP AI CAR by Yeqi, Yuan, Chang')
root.geometry('1200x600')

#canvas = tk.Canvas(root,bg='pink',height=200,width=540)
# image_path1 = tk.PhotoImage(file='1.png')
# image_path2 = tk.PhotoImage(file='tenor.gif')
# image1 = canvas.create_image(10,10,anchor='nw',image=image_path1)
# image2 = canvas.create_image(293,-30,anchor='nw',image=image_path2)
#canvas.pack()

frm_l =tk.Frame(root)
frm_r =tk.Frame(root)

frm_l.pack(side='left')
frm_r.pack(side='right')
#===================================================================
def hit_me1():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('run forward 1s')

def hit_me2():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn left 1s')

def hit_me3():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn right 1s')

def hit_me4():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('make a turn 180 degree')

def hit_me5():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('run forward a bit')

def hit_me6():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn left a bit')

def hit_me7():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('turn right a bit')

def hit_me8():
    on_hit = False
    if on_hit == False:
        on_hit =True
        var.set('rotate a bit')
    
        
# #===================================================================
# # ll = tk.Label(frm_l,text='discrete control',bg='yellow',font=('Arial',12),width=15,height=3)
# # ll.pack()

# # bl1 = tk.Button(frm_l,text='run forward',width=15,height=3,command=hit_me1)
# # bl1.pack(side='top')

# # bl2 = tk.Button(frm_l,text='turn left',width=15,height=3,command=hit_me2)
# # bl2.pack(side='left')

# # bl3 = tk.Button(frm_l,text='turn right',width=15,height=3,command=hit_me3)
# # bl3.pack(side='right')

# # bl4 = tk.Button(frm_l,text='make a turn',width=15,height=3,command=hit_me4)
# # bl4.pack(side='bottom')
#===================================================================
lr = tk.Label(frm_r,text='continous control',bg='yellow',font=('Arial',12),width=15,height=3)
lr.pack()

br1 = tk.Button(frm_r,text='run forward',width=15,height=3,command=hit_me5)
br1.pack(side='top')

br2 = tk.Button(frm_r,text='turn left',width=15,height=3,command=hit_me6)
br2.pack(side='left')

br3 = tk.Button(frm_r,text='turn right',width=15,height=3,command=hit_me7)
br3.pack(side='right')

br4 = tk.Button(frm_r,text='make a turn',width=15,height=3,command=hit_me8)
br4.pack(side='bottom')
#===================================================================
lmain = tk.Label(root, compound=tk.CENTER, anchor=tk.CENTER, relief=tk.RAISED)
#button = tk.Button(root, text="Capture")
lmain.pack()
#button.place(bordermode=tk.INSIDE, relx=0.5, rely=0.9, anchor=tk.CENTER, width=300, height=50)
#button.focus()
#===================================================================
cap = cv2.VideoCapture(0)
var = tk.StringVar()            
def show_frame():
    global var,cancel, prevImg, button

    _, frame = cap.read()
    cv2image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGBA)
    
    cv2.rectangle(cv2image,(30,80),(280,420),(255,0,0),5)
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(cv2image,'Put your RIGHT hand in this rectangle!',(20,60),font,0.6,(0,255,0),2,cv2.LINE_AA)
    
    crop_cv2image = cv2image[80:420, 30:280]
    cv2image_gray = cv2.cvtColor(crop_cv2image, cv2.COLOR_RGB2GRAY)
    img = cv2.resize(cv2image_gray,dsize=(28,28),interpolation=cv2.INTER_LINEAR)
    img = img.astype('float32')
    img *= (1/255)
    img = img.reshape((1,)+img.shape + (1,))
    prediction = model.predict(img)
    print(prediction)
    if prediction[0][1]>=0.4:
        var = 'run forward'
    if prediction[0][2]>=0.4:
        var = 'turn left'
    if prediction[0][3]>=0.4:
        var = 'turn right'
    if prediction[0][0]>=0.4:
        var = 'no instruction'  
    print(var)
    
    l = tk.Label(root,textvariable=var,bg='blue',font=('Arial',22),width=25,height=3)
    l.pack(side='bottom')


    prevImg = Image.fromarray(cv2image)
    imgtk = ImageTk.PhotoImage(image=prevImg)
    lmain.imgtk = imgtk
    lmain.configure(image=imgtk)
    if not cancel:
        lmain.after(10, show_frame)
        
show_frame()


root.mainloop()

[[2.3750389e-02 4.0161201e-01 3.6635824e-06 5.7463396e-01]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.1436770

[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn right
[[0.26494372 0.37224123 0.21913794 0.14367706]]
turn rig

[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.14367706]]
run forward
[[0.26494372 0.37224123 0.21913794 0.143

[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.8657355e-26]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 5.9296093e-27]]
run forward
[[0.000000e+00 1.000000e+00 0.000000e+00 9.138736e-27]]
run forward
[[0.000000e+00 1.000000e+00 0.000000e+00 1.110661e-27]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1818352e-30]]
run forward
[[0.000000e+00 1.000000e+00 0.000000e+00 7.155485e-32]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.5118723e-30]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.5225229e-29]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.1198052e-29]]
run forward
[[0.000000e+00 1.000000e+00 0.000000e+00 7.275696e-29]]
run forward
[[0.00000e+00 1.00000e+00 0.00000e+00 2.18577e-28]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.3115314e-29]]
run forward
[[0.000000e+00 1.000000e+00 0.000000e+00 9.954272e-27]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 5.4067436e-26]]
run forward
[[0.0000000e+00 1.00

[[4.9214077e-06 8.1308978e-03 2.7186077e-05 9.9183697e-01]]
turn right
[[8.2286867e-08 1.5917642e-03 7.0772495e-07 9.9840742e-01]]
turn right
[[4.1461563e-13 6.8127044e-08 1.4822106e-03 9.9851769e-01]]
turn right
[[5.332908e-30 5.231826e-11 9.999999e-01 6.163220e-08]]
turn left
[[2.5449016e-33 1.7703962e-11 1.0000000e+00 1.4933745e-09]]
turn left
[[0.0000000e+00 6.9768457e-14 1.0000000e+00 1.7100049e-13]]
turn left
[[0.0000000e+00 1.4721937e-14 1.0000000e+00 3.0525877e-15]]
turn left
[[0.0000000e+00 1.5485483e-13 1.0000000e+00 4.9723460e-18]]
turn left
[[0.0000000e+00 6.2919915e-18 1.0000000e+00 1.6186546e-20]]
turn left
[[0.0000000e+00 9.5128118e-23 1.0000000e+00 1.5141638e-23]]
turn left
[[0.0000000e+00 7.1229227e-22 1.0000000e+00 3.4063180e-22]]
turn left
[[0.0000000e+00 5.8807901e-21 1.0000000e+00 2.4269796e-20]]
turn left
[[0.0000000e+00 2.6080735e-20 1.0000000e+00 9.6286331e-20]]
turn left
[[0.0000000e+00 2.1818812e-19 1.0000000e+00 1.5200476e-18]]
turn left
[[0.0000000e+00 2.963

[[4.9269228e-31 7.8907686e-10 1.0000000e+00 6.4838548e-13]]
turn left
[[6.3165038e-31 5.9969379e-10 1.0000000e+00 4.1740764e-13]]
turn left
[[1.10538735e-32 1.40297246e-10 1.00000000e+00 1.24927073e-13]]
turn left
[[2.6180008e-28 6.1283325e-09 1.0000000e+00 6.4811503e-12]]
turn left
[[1.5979275e-31 2.4582858e-10 1.0000000e+00 1.3476751e-13]]
turn left
[[5.5369710e-32 1.3224226e-10 1.0000000e+00 3.7871944e-14]]
turn left
[[3.2706190e-36 4.8763450e-12 1.0000000e+00 1.1214987e-15]]
turn left
[[2.0889483e-36 8.1625730e-12 1.0000000e+00 1.1713639e-15]]
turn left
[[0.0000000e+00 8.4798477e-13 1.0000000e+00 1.6040960e-16]]
turn left
[[1.0462143e-36 5.9934210e-12 1.0000000e+00 1.2272651e-15]]
turn left
[[1.8102099e-34 3.6886966e-11 1.0000000e+00 7.9669225e-15]]
turn left
[[6.1449481e-33 7.2139808e-11 1.0000000e+00 1.7815346e-14]]
turn left
[[7.1367228e-34 3.4225858e-11 1.0000000e+00 9.7578526e-15]]
turn left
[[5.8537753e-36 5.4776678e-12 1.0000000e+00 2.2290568e-15]]
turn left
[[9.3779992e-35 

[[0.0000000e+00 3.9929198e-35 1.0000000e+00 2.6657990e-36]]
turn left
[[0.0000000e+00 4.0266495e-34 1.0000000e+00 1.0803274e-35]]
turn left
[[0.0000000e+00 3.1865436e-35 1.0000000e+00 1.5725200e-36]]
turn left
[[0.0000000e+00 9.7437899e-38 1.0000000e+00 1.2003957e-38]]
turn left
[[0.0000000e+00 1.3522341e-37 1.0000000e+00 0.0000000e+00]]
turn left
[[0.0000000e+00 1.5446716e-36 1.0000000e+00 3.7577696e-38]]
turn left
[[0.0000000e+00 6.3474502e-37 1.0000000e+00 2.9087016e-38]]
turn left
[[0.0000000e+00 7.6335140e-35 1.0000000e+00 7.9033614e-36]]
turn left
[[0.0000000e+00 9.6967925e-34 1.0000000e+00 1.2508859e-34]]
turn left
[[0.0000000e+00 1.1289573e-33 1.0000000e+00 1.7809083e-34]]
turn left
[[0.0000000e+00 6.8076075e-31 1.0000000e+00 5.7189012e-33]]
turn left
[[0.00000000e+00 8.04746893e-30 1.00000000e+00 1.19057624e-32]]
turn left
[[0.0000000e+00 1.9638762e-28 1.0000000e+00 9.4688521e-32]]
turn left
[[0.0000000e+00 1.8186189e-27 1.0000000e+00 1.0863762e-30]]
turn left
[[0.0000000e+00 

[[2.5563894e-04 2.4313374e-01 7.5656438e-01 4.6223948e-05]]
turn left
[[2.9249085e-04 2.6889259e-01 7.3077267e-01 4.2285163e-05]]
turn left
[[4.347359e-04 2.851223e-01 7.143805e-01 6.243404e-05]]
turn left
[[1.6447088e-04 2.1057634e-01 7.8921980e-01 3.9305025e-05]]
turn left
[[2.1868120e-05 1.6093871e-01 8.3902669e-01 1.2728063e-05]]
turn left
[[4.1354378e-05 1.2078263e-01 8.7915033e-01 2.5669757e-05]]
turn left
[[2.5147727e-05 1.1555937e-01 8.8440186e-01 1.3685850e-05]]
turn left
[[2.8132175e-05 1.2862770e-01 8.7132853e-01 1.5670314e-05]]
turn left
[[1.9375248e-05 1.1757771e-01 8.8239145e-01 1.1473676e-05]]
turn left
[[1.1923699e-05 9.4057940e-02 9.0592253e-01 7.5516896e-06]]
turn left
[[2.0425277e-05 9.9131502e-02 9.0083522e-01 1.2905165e-05]]
turn left
[[2.6015969e-05 9.0030476e-02 9.0992427e-01 1.9287460e-05]]
turn left
[[6.9115464e-05 9.9078104e-02 9.0080065e-01 5.2082454e-05]]
turn left
[[6.1996182e-04 1.7740925e-01 8.2151622e-01 4.5456368e-04]]
turn left
[[9.4764639e-04 1.979896

[[7.7534340e-26 5.3891919e-10 1.0000000e+00 4.7084596e-14]]
turn left
[[2.9952451e-24 1.9193971e-09 1.0000000e+00 3.4164322e-13]]
turn left
[[8.3517414e-24 2.2225766e-09 1.0000000e+00 5.8782124e-13]]
turn left
[[1.8558406e-26 8.3734619e-10 1.0000000e+00 5.0073799e-14]]
turn left
[[1.4809047e-25 1.9669091e-09 1.0000000e+00 1.6430096e-13]]
turn left
[[2.3183434e-26 1.1929565e-09 1.0000000e+00 7.0059830e-14]]
turn left
[[4.209138e-26 6.775257e-10 1.000000e+00 5.998939e-14]]
turn left
[[1.6636283e-26 8.0837032e-10 1.0000000e+00 5.2777424e-14]]
turn left
[[6.9810098e-26 1.3308264e-09 1.0000000e+00 1.0276005e-13]]
turn left
[[5.9017205e-26 4.9260546e-10 1.0000000e+00 6.3666581e-14]]
turn left
[[8.6899246e-27 9.7902786e-10 1.0000000e+00 4.4082891e-14]]
turn left
[[6.0740248e-27 1.2599748e-09 1.0000000e+00 4.2027539e-14]]
turn left
[[7.0866450e-26 2.9018954e-09 1.0000000e+00 1.3532723e-13]]
turn left
[[9.1285628e-27 1.2616774e-09 1.0000000e+00 5.4837879e-14]]
turn left
[[5.7790078e-27 1.084576

[[0.00253121 0.0346422  0.96009564 0.00273095]]
turn left
[[0.00463466 0.04805404 0.94268924 0.00462205]]
turn left
[[0.00735229 0.06312774 0.92278385 0.00673614]]
turn left
[[0.01613209 0.08588304 0.88660914 0.01137576]]
turn left
[[0.01197199 0.0769309  0.90203637 0.00906074]]
turn left
[[0.00669692 0.0552099  0.9325076  0.00558562]]
turn left
[[0.0071918  0.05826844 0.92930895 0.00523084]]
turn left
[[0.01014191 0.07366784 0.9100916  0.00609863]]
turn left
[[0.01743773 0.08743034 0.8868174  0.00831449]]
turn left
[[0.01663253 0.08497625 0.89042753 0.00796369]]
turn left
[[0.04319709 0.17312533 0.77213484 0.01154282]]
turn left
[[0.0666228  0.19495639 0.72082245 0.01759839]]
turn left
[[0.10119317 0.2465257  0.62560755 0.02667349]]
turn left
[[0.09974563 0.23657204 0.6319217  0.03176063]]
turn left
[[0.09568496 0.23661453 0.6421011  0.02559938]]
turn left
[[0.01759414 0.08509348 0.8927519  0.0045605 ]]
turn left
[[1.9593183e-04 5.6692893e-03 9.9387884e-01 2.5594913e-04]]
turn left
[[

[[3.2410986e-05 2.4597902e-02 9.7511983e-01 2.4977876e-04]]
turn left
[[6.2831305e-04 9.1988832e-02 9.0560734e-01 1.7755871e-03]]
turn left
[[0.01104983 0.28325176 0.6918546  0.01384385]]
turn left
[[0.02765367 0.46465504 0.49028468 0.01740653]]
turn left
[[5.8065561e-06 9.9370790e-01 5.8159363e-03 4.7025841e-04]]
run forward
[[0.0000000e+00 1.0000000e+00 4.6948053e-35 2.9065025e-10]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.0733553e-22]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.8190467e-32]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 3.9438557e-36]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.7087682e-38]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 9.3304595e-37]]
run forward
[[0. 1. 0. 0.]]
run forward
[[0. 1. 0. 0.]]
run forward
[[3.55464e-29 1.

[[0.0000000e+00 1.0000000e+00 5.0613006e-31 3.8732755e-20]]
run forward
[[0.000000e+00 1.000000e+00 3.653525e-30 4.934563e-22]]
run forward
[[0.0000000e+00 1.0000000e+00 1.3166043e-28 1.9231305e-21]]
run forward
[[0.0000000e+00 1.0000000e+00 1.3219590e-28 7.0557254e-13]]
run forward
[[0.0000000e+00 1.0000000e+00 1.7412904e-30 2.2564314e-17]]
run forward
[[0.0000000e+00 1.0000000e+00 4.7615650e-32 1.2317805e-17]]
run forward
[[0.0000000e+00 1.0000000e+00 1.3861505e-30 9.0680698e-19]]
run forward
[[0.0000000e+00 1.0000000e+00 9.5457899e-29 1.2880056e-20]]
run forward
[[0.0000000e+00 1.0000000e+00 1.1958223e-28 2.0590323e-16]]
run forward
[[0.0000000e+00 1.0000000e+00 8.1701108e-31 5.2278897e-21]]
run forward
[[0.00000000e+00 1.00000000e+00 1.10597535e-29 1.85480777e-18]]
run forward
[[0.0000000e+00 1.0000000e+00 1.2578843e-30 4.1852030e-18]]
run forward
[[0.0000000e+00 1.0000000e+00 1.6278038e-31 7.9543689e-18]]
run forward
[[0.000000e+00 1.000000e+00 7.943681e-29 7.167064e-18]]
run forw

[[5.7677041e-17 6.5059081e-04 9.9934942e-01 2.3624988e-15]]
turn left
[[3.0236145e-17 1.2861125e-04 9.9987137e-01 4.6617686e-16]]
turn left
[[6.5106534e-18 2.5140738e-05 9.9997485e-01 2.8478576e-16]]
turn left
[[7.2759477e-18 1.5510582e-06 9.9999845e-01 1.6808191e-16]]
turn left
[[4.470398e-17 2.361544e-08 1.000000e+00 9.642542e-17]]
turn left
[[2.5757880e-15 2.8022467e-09 1.0000000e+00 1.0407209e-14]]
turn left
[[3.8187215e-16 7.0336497e-09 1.0000000e+00 1.1822770e-15]]
turn left
[[1.7935789e-15 1.1859542e-03 9.9881411e-01 3.6218546e-13]]
turn left
[[3.9724831e-13 2.3084381e-06 9.9999774e-01 4.5095518e-09]]
turn left
[[5.4715887e-10 3.4374048e-04 9.9965537e-01 7.8710178e-07]]
turn left
[[1.3426953e-06 8.4198918e-03 9.9024838e-01 1.3303921e-03]]
turn left
[[3.4290400e-07 2.1275798e-02 9.7499901e-01 3.7247411e-03]]
turn left
[[1.2885236e-07 6.8911193e-03 9.9217695e-01 9.3179726e-04]]
turn left
[[3.3520596e-06 2.5283655e-02 9.6329182e-01 1.1421260e-02]]
turn left
[[3.2135136e-05 1.041593

[[0.0000000e+00 1.0000000e+00 3.7986464e-29 2.3860640e-28]]
run forward
[[0.0000000e+00 1.0000000e+00 6.7330276e-29 3.8246484e-27]]
run forward
[[0.0000000e+00 1.0000000e+00 1.4286106e-27 2.4286868e-25]]
run forward
[[0.0000000e+00 1.0000000e+00 4.2844445e-29 5.1978072e-27]]
run forward
[[0.0000000e+00 1.0000000e+00 6.2330754e-27 7.1355921e-23]]
run forward
[[0.000000e+00 1.000000e+00 1.777026e-27 7.987297e-26]]
run forward
[[0.000000e+00 1.000000e+00 7.241614e-28 8.049117e-25]]
run forward
[[0.0000000e+00 1.0000000e+00 2.3117429e-29 1.7665230e-27]]
run forward
[[0.000000e+00 1.000000e+00 9.518216e-24 7.125419e-23]]
run forward
[[0.0000000e+00 1.0000000e+00 1.8190297e-18 6.8534104e-17]]
run forward
[[0.0000000e+00 1.0000000e+00 5.3262374e-16 7.2517838e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 3.8494163e-11 1.2681552e-09]]
run forward
[[0.0000000e+00 9.9965847e-01 3.4158671e-04 4.7682271e-09]]
run forward
[[0.000000e+00 9.604605e-01 3.952365e-02 1.589889e-05]]
run forward
[[0.0000

[[0.0000000e+00 1.0000000e+00 1.1745891e-24 5.0192269e-18]]
run forward
[[0.0000000e+00 1.0000000e+00 1.9294749e-18 8.6049982e-16]]
run forward
[[0.0000000e+00 1.0000000e+00 1.6544250e-20 1.6145139e-16]]
run forward
[[0.0000000e+00 1.0000000e+00 5.4881973e-20 2.9673728e-15]]
run forward
[[0.0000000e+00 1.0000000e+00 1.2403191e-18 2.4955410e-14]]
run forward
[[0.000000e+00 1.000000e+00 4.225678e-18 5.534443e-15]]
run forward
[[0.0000000e+00 1.0000000e+00 1.2950967e-18 1.0619797e-15]]
run forward
[[0.0000000e+00 1.0000000e+00 2.3648654e-16 3.0285813e-13]]
run forward
[[0.0000000e+00 1.0000000e+00 6.5306240e-16 2.8451308e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 5.2217845e-16 3.7467079e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 4.4933790e-16 1.4333364e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 2.9823736e-16 9.0726261e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 2.4541697e-16 5.4626690e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 8.6476499e-15 2.9516382e-13]]
run forw

[[0.0000000e+00 1.0000000e+00 5.9649253e-37 9.8202939e-29]]
run forward
[[0.0000000e+00 1.0000000e+00 2.0069132e-38 4.2618655e-30]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.4164254e-31]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 7.5525106e-32]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.6513217e-29]]
run forward
[[0.0000000e+00 1.0000000e+00 3.2877029e-38 1.8264803e-29]]
run forward
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 6.4148485e-31]]
run forward
[[0.0000000e+00 1.0000000e+00 2.3496176e-36 1.4979302e-28]]
run forward
[[0.0000000e+00 1.0000000e+00 2.1129295e-34 4.9662141e-29]]
run forward
[[0.0000000e+00 1.0000000e+00 1.9112465e-28 2.9048620e-25]]
run forward
[[0.0000000e+00 1.0000000e+00 9.6709212e-29 2.1558792e-25]]
run forward
[[0.0000000e+00 1.0000000e+00 1.7964904e-29 9.4039431e-26]]
run forward
[[0.0000000e+00 1.0000000e+00 6.8835686e-32 1.1148676e-27]]
run forward
[[0.0000000e+00 1.0000000e+00 1.9587246e-32 1.4095881e-27]]
run 

[[0.000000e+00 1.000000e+00 7.092326e-18 5.553109e-10]]
run forward
[[0.0000000e+00 1.0000000e+00 1.8726122e-23 6.4139562e-12]]
run forward
[[0.0000000e+00 1.0000000e+00 3.5336986e-21 2.2924267e-11]]
run forward
[[0.0000000e+00 1.0000000e+00 3.1364349e-20 2.6293948e-10]]
run forward
[[0.0000000e+00 1.0000000e+00 4.3497082e-21 4.1646572e-11]]
run forward
[[0.0000000e+00 1.0000000e+00 3.9846546e-29 3.1473982e-22]]
run forward
[[0.0000000e+00 1.0000000e+00 6.9333553e-23 2.7616097e-19]]
run forward
[[0.0000000e+00 1.0000000e+00 2.0372379e-20 2.3051414e-19]]
run forward
[[0.0000000e+00 1.0000000e+00 4.2891148e-17 3.7316216e-19]]
run forward
[[0.0000000e+00 1.0000000e+00 2.0274859e-19 3.6134587e-20]]
run forward
[[0.0000000e+00 1.0000000e+00 3.9400923e-23 1.3861931e-22]]
run forward
[[0.0000000e+00 1.0000000e+00 1.2090527e-25 1.9991565e-24]]
run forward
[[0.0000000e+00 1.0000000e+00 3.4011807e-27 8.9156073e-26]]
run forward
[[0.0000000e+00 1.0000000e+00 7.7982998e-22 8.5775655e-24]]
run forw

[[0.0000000e+00 1.0000000e+00 2.1388927e-15 1.6260490e-14]]
run forward
[[0.0000000e+00 1.0000000e+00 4.0163467e-16 1.2493262e-12]]
run forward
[[0.000000e+00 1.000000e+00 5.566709e-16 2.232660e-12]]
run forward
[[0.0000000e+00 1.0000000e+00 2.6098006e-16 5.8588061e-12]]
run forward
[[0.0000000e+00 1.0000000e+00 1.2450607e-16 3.0912290e-11]]
run forward
[[0.0000000e+00 1.0000000e+00 1.0445023e-16 8.9402262e-12]]
run forward
[[0.0000000e+00 1.0000000e+00 7.9474108e-21 3.2813422e-13]]
run forward
[[0.00000000e+00 1.00000000e+00 1.01627897e-22 4.04431508e-15]]
run forward
[[0.0000000e+00 1.0000000e+00 2.8066450e-23 2.2643666e-15]]
run forward
[[0.0000000e+00 1.0000000e+00 4.1088783e-24 4.8164824e-16]]
run forward
[[0.000000e+00 1.000000e+00 7.241645e-27 5.991028e-17]]
run forward
[[0.0000000e+00 1.0000000e+00 1.8882974e-26 4.7418096e-16]]
run forward
[[0.0000000e+00 1.0000000e+00 5.9889935e-25 1.4349270e-16]]
run forward
[[0.0000000e+00 1.0000000e+00 6.2984433e-28 9.4634716e-17]]
run forw

[[0.0000000e+00 3.4416219e-15 1.0000000e+00 4.2842712e-26]]
turn left
[[0.0000000e+00 2.2122743e-16 1.0000000e+00 3.2442353e-23]]
turn left
[[0.000000e+00 7.500284e-05 9.999250e-01 2.511197e-13]]
turn left
[[0.0000000e+00 6.7022051e-20 1.0000000e+00 1.9430458e-23]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 4.3773352e-23]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 5.9932883e-18]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 2.3773282e-17]]
turn left
[[3.7961348e-24 0.0000000e+00 9.9993491e-01 6.5090710e-05]]
turn left
[[0.000000e+00 0.000000e+00 9.878413e-30 1.000000e+00]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0.000000e+00 8.979585e-23 0.000000e+00 1.000000e+00]]
turn right
[[5.6694935e-30 5.4616900e-29 0.0000000e+00 1.0000000e+00]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0. 0. 0. 1.]]
turn right
[[0.00000e+00 9.67499e-27 1.00000e+00 0.00000e+00]

[[0.0000000e+00 1.3805311e-29 1.0000000e+00 1.6709985e-35]]
turn left
[[0.0000000e+00 6.2982174e-31 1.0000000e+00 1.7760141e-37]]
turn left
[[0.0000000e+00 1.7856952e-29 1.0000000e+00 2.5571825e-33]]
turn left
[[0.0000000e+00 8.0005680e-32 1.0000000e+00 6.9659107e-38]]
turn left
[[0.0000000e+00 4.9552334e-31 1.0000000e+00 7.1336052e-38]]
turn left
[[0.000000e+00 2.035207e-31 1.000000e+00 0.000000e+00]]
turn left
[[0.0000000e+00 4.9587454e-33 1.0000000e+00 0.0000000e+00]]
turn left
[[0.000000e+00 6.729595e-34 1.000000e+00 0.000000e+00]]
turn left
[[0.0000000e+00 3.2493505e-38 1.0000000e+00 0.0000000e+00]]
turn left
[[0.000000e+00 5.431215e-35 1.000000e+00 0.000000e+00]]
turn left
[[0.0000000e+00 1.3993234e-34 1.0000000e+00 0.0000000e+00]]
turn left
[[0.000000e+00 7.114644e-36 1.000000e+00 0.000000e+00]]
turn left
[[0.000000e+00 3.245662e-36 1.000000e+00 0.000000e+00]]
turn left
[[0.000000e+00 6.722375e-37 1.000000e+00 0.000000e+00]]
turn left
[[0.0000000e+00 1.2763293e-37 1.0000000e+00 

[[0.         0.9947003  0.00248822 0.00281153]]
run forward
[[0.0000000e+00 9.8103541e-01 1.8941555e-02 2.3064931e-05]]
run forward
[[0.0000000e+00 8.8900703e-01 1.1099248e-01 4.7731504e-07]]
run forward
[[0.0000000e+00 4.6583705e-02 9.5341438e-01 1.9081153e-06]]
turn left
[[0.0000000e+00 3.3265420e-05 9.9996674e-01 2.7451155e-09]]
turn left
[[0.0000000e+00 7.8878158e-01 2.1121526e-01 3.0939173e-06]]
run forward
[[0.000000e+00 9.989189e-01 1.079424e-03 1.683175e-06]]
run forward
[[0.0000000e+00 9.8926884e-01 1.0697434e-02 3.3692537e-05]]
run forward
[[0.0000000e+00 9.2379385e-01 7.6197296e-02 8.7817534e-06]]
run forward
[[0.0000000e+00 3.5441451e-02 9.6455741e-01 1.1997207e-06]]
turn left
[[0.0000000e+00 9.4622862e-01 5.3770885e-02 5.2896939e-07]]
run forward
[[0.0000000e+00 9.8853940e-01 1.1460511e-02 1.3399939e-07]]
run forward
[[0.0000000e+00 5.4452877e-04 9.9945551e-01 7.0566575e-10]]
turn left
[[0.000000e+00 1.541876e-05 9.999846e-01 8.342876e-12]]
turn left
[[0.0000000e+00 9.7682

[[0.0000000e+00 2.7845148e-02 1.3188212e-28 9.7215492e-01]]
turn right
[[0.0000000e+00 4.6681821e-02 1.0804299e-27 9.5331818e-01]]
turn right
[[0.0000000e+00 4.5299949e-03 5.3176918e-29 9.9547005e-01]]
turn right
[[0.0000000e+00 5.0180968e-02 2.6245501e-27 9.4981903e-01]]
turn right
[[0.0000000e+00 5.7771128e-01 6.9973411e-26 4.2228872e-01]]
turn right
[[0.0000000e+00 1.2080137e-01 3.1083783e-27 8.7919861e-01]]
turn right
[[0.0000000e+00 8.7774366e-02 1.6701492e-25 9.1222566e-01]]
turn right
[[0.0000000e+00 7.9806447e-03 1.8119213e-25 9.9201936e-01]]
turn right
[[0.0000000e+00 4.0194462e-04 3.2037987e-27 9.9959809e-01]]
turn right
[[0.0000000e+00 4.7472771e-02 2.4500061e-26 9.5252723e-01]]
turn right
[[0.0000000e+00 9.1665500e-01 6.4813305e-26 8.3344944e-02]]
run forward
[[0.0000000e+00 5.0534230e-01 2.7542740e-26 4.9465775e-01]]
turn right
[[0.000000e+00 6.257526e-01 1.050050e-25 3.742474e-01]]
run forward
[[0.0000000e+00 9.4016111e-01 5.9487916e-27 5.9838947e-02]]
run forward
[[0.000

[[0.0000000e+00 9.9826968e-01 2.2676290e-12 1.7303093e-03]]
run forward
[[0.0000000e+00 9.9774384e-01 8.4137254e-13 2.2561797e-03]]
run forward
[[0.0000000e+00 9.8789364e-01 3.5849233e-08 1.2106362e-02]]
run forward
[[0.0000000e+00 9.9676102e-01 2.9372410e-08 3.2390195e-03]]
run forward
[[0.0000000e+00 9.9800235e-01 2.7418480e-07 1.9973849e-03]]
run forward
[[0.0000000e+00 9.9592531e-01 1.6505389e-06 4.0730550e-03]]
run forward
[[0.0000000e+00 9.9397981e-01 5.7577455e-07 6.0195709e-03]]
run forward
[[0.0000000e+00 9.8658895e-01 1.5781062e-06 1.3409497e-02]]
run forward
[[0.0000000e+00 9.9828607e-01 1.2793197e-06 1.7126073e-03]]
run forward
[[0.0000000e+00 9.8953712e-01 2.4148876e-06 1.0460559e-02]]
run forward
[[4.6397889e-38 9.9819845e-01 1.8426841e-06 1.7998294e-03]]
run forward
[[0.0000000e+00 9.9348241e-01 3.4106183e-08 6.5175234e-03]]
run forward
[[0.0000000e+00 9.9537992e-01 9.5541908e-10 4.6201036e-03]]
run forward
[[0.0000000e+00 9.9900973e-01 2.6583718e-11 9.9023606e-04]]
run 

[[0.0000000e+00 4.6341781e-02 3.5448216e-17 9.5365828e-01]]
turn right
[[0.0000000e+00 1.3589914e-02 3.6401548e-16 9.8641008e-01]]
turn right
[[0.0000000e+00 2.3093403e-03 2.2813324e-16 9.9769068e-01]]
turn right
[[0.0000000e+00 1.1330796e-01 5.3525547e-17 8.8669205e-01]]
turn right
[[0.0000000e+00 1.7683518e-03 3.2393733e-17 9.9823171e-01]]
turn right
[[0.00000000e+00 1.00492455e-01 1.33023758e-16 8.99507582e-01]]
turn right
[[0.0000000e+00 7.8841951e-04 1.5966843e-18 9.9921155e-01]]
turn right
[[0.0000000e+00 7.3613126e-07 2.3813746e-17 9.9999928e-01]]
turn right
[[0.0000000e+00 5.7858520e-06 1.2852829e-14 9.9999416e-01]]
turn right
[[7.5615502e-34 8.2430657e-04 4.4327250e-12 9.9917573e-01]]
turn right
[[3.2205499e-28 9.8840928e-01 1.3206503e-09 1.1590673e-02]]
run forward
[[3.7206952e-27 5.6291133e-01 3.5407760e-05 4.3705326e-01]]
turn right
[[1.2077015e-25 3.9067739e-01 1.8034623e-03 6.0751921e-01]]
turn right
[[1.4308028e-23 7.2137088e-02 1.5665086e-02 9.1219789e-01]]
turn right
[

[[0.0000000e+00 2.1289257e-33 1.0000000e+00 7.3908975e-20]]
turn left
[[0.0000000e+00 1.1514988e-36 1.0000000e+00 5.9093438e-23]]
turn left
[[0.000000e+00 0.000000e+00 1.000000e+00 4.462421e-26]]
turn left
[[0.000000e+00 0.000000e+00 1.000000e+00 8.322565e-27]]
turn left
[[0.000000e+00 0.000000e+00 1.000000e+00 2.707106e-30]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 2.0019666e-30]]
turn left
[[0.000000e+00 0.000000e+00 1.000000e+00 4.994719e-34]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 3.2637068e-33]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.3946002e-29]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 2.1747229e-30]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 5.7376556e-31]]
turn left
[[0.000000e+00 0.000000e+00 1.000000e+00 5.187236e-32]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.5929475e-33]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 7.3023115e-35]]
turn left
[[0.0000000e+00 0.0000000e+00 1.0000000e